# Generated by Django 5.2.7 on 2025-11-22 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_scanresult_result'),
    ]

    operations = [
        migrations.AddField(
            model_name='scanresult',
            name='reason',
            field=models.TextField(blank=True, null=True),
        ),
    ]
