"""
Django settings for phish_guard_backend project.

Generated by 'django-admin startproject' using Django 5.2.6.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
# This defines the base directory for the Django project
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
# This secret key is used for cryptographic signing and should be kept secure
SECRET_KEY = 'django-insecure-*i@sx0azccfjqq8ao%t_u#e103)z)qh&5izr$(yw4*om*!1^60'

# SECURITY WARNING: don't run with debug turned on in production!
# Debug mode provides detailed error pages and should be disabled in production
DEBUG = True

# Allowed hosts for the Django application
# '*' allows all hosts - suitable for development only
ALLOWED_HOSTS = ['*']  # For testing only - should be restricted in production


# Application definition
# List of Django applications that are enabled in this project

INSTALLED_APPS = [
    'corsheaders',  # Add corsheaders for cross-origin resource sharing
    'rest_framework',  # Django REST Framework for API development
    'api.apps.ApiConfig',  # Our custom API application
    'django.contrib.admin',  # Django admin interface
    'django.contrib.auth',  # Django authentication system
    'django.contrib.contenttypes',  # Django content types framework
    'django.contrib.sessions',  # Django session framework
    'django.contrib.messages',  # Django messaging framework
    'django.contrib.staticfiles',  # Django static files handling
]

# Middleware configuration
# Middleware classes are executed in the order listed
MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',  # CORS middleware must be first
    'django.middleware.security.SecurityMiddleware',  # Security enhancements
    'django.contrib.sessions.middleware.SessionMiddleware',  # Session management
    'django.middleware.common.CommonMiddleware',  # Common functionality
    'django.middleware.csrf.CsrfViewMiddleware',  # CSRF protection
    'django.contrib.auth.middleware.AuthenticationMiddleware',  # User authentication
    'django.contrib.messages.middleware.MessageMiddleware',  # Message handling
    'django.middleware.clickjacking.XFrameOptionsMiddleware',  # Clickjacking protection
]

# CORS settings - Comprehensive settings for cross-origin requests
# CORS_ALLOW_ALL_ORIGINS should only be True for development
CORS_ALLOW_ALL_ORIGINS = True  # For testing only - restrict in production
CORS_ALLOW_CREDENTIALS = True  # Allow credentials in CORS requests

# Specific allowed origins for CORS requests
CORS_ALLOWED_ORIGINS = [
    "http://localhost:3000",  # React development server
    "http://127.0.0.1:3000",  # React development server (alternative)
    "http://localhost:8080",  # Vue.js development server
    "http://127.0.0.1:8080",  # Vue.js development server (alternative)
    "http://localhost:5173",  # Vite development server
    "http://127.0.0.1:5173",  # Vite development server (alternative)
    "http://localhost:4200",  # Angular development server
    "http://127.0.0.1:4200",  # Angular development server (alternative)
]

# Additional CORS headers that are allowed
CORS_ALLOW_HEADERS = [
    'accept',
    'accept-encoding',
    'authorization',
    'content-type',
    'dnt',
    'origin',
    'user-agent',
    'x-csrftoken',
    'x-requested-with',
]

# HTTP methods allowed for CORS requests
CORS_ALLOW_METHODS = [
    'DELETE',
    'GET',
    'OPTIONS',
    'PATCH',
    'POST',
    'PUT',
]


# URL configuration
# Points to the main URL configuration module
ROOT_URLCONF = 'phish_guard_backend.urls'

# Template configuration
# Defines how Django templates are loaded and processed
TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],  # Additional template directories
        'APP_DIRS': True,  # Look for templates in app directories
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',  # Request context
                'django.contrib.auth.context_processors.auth',  # User context
                'django.contrib.messages.context_processors.messages',  # Messages context
            ],
        },
    },
]

# WSGI application configuration
# Points to the WSGI application for deployment
WSGI_APPLICATION = 'phish_guard_backend.wsgi.application'


# Database configuration
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

# PostgreSQL database configuration for production use
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',  # PostgreSQL database engine
        'NAME': 'phish_guard_backend',  # Database name
        'USER': 'postgres',  # Database user
        'PASSWORD': '123',  # Database password
        'HOST': 'localhost',  # Database host
        'PORT': '5432',  # Database port
    }
}

# Alternative SQLite database configuration (commented out)
# Uncomment this section and comment out the PostgreSQL configuration above
# to use SQLite for development
# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.sqlite3',
#         'NAME': BASE_DIR / 'db.sqlite3',
#     }
# }


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

# Password validation rules for user authentication
AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

# Language and timezone settings
LANGUAGE_CODE = 'en-us'  # Default language for the application
TIME_ZONE = 'UTC'  # Default timezone
USE_I18N = True  # Enable internationalization
USE_TZ = True  # Enable timezone support


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

# URL prefix for static files
STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

# Use BigAutoField as the default primary key field type
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


# REST Framework settings
# Configuration for Django REST Framework
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [],  # No authentication required for API
    'DEFAULT_PERMISSION_CLASSES': [],  # No permissions required for API
    'DEFAULT_RENDERER_CLASSES': [
        'rest_framework.renderers.JSONRenderer',  # Use JSON for API responses
    ],
    'DEFAULT_PARSER_CLASSES': [
        'rest_framework.parsers.JSONParser',  # Parse JSON requests
        'rest_framework.parsers.FormParser',  # Parse form data
        'rest_framework.parsers.MultiPartParser',  # Parse multipart data
    ],
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 20,  # Number of items per page
}

# Additional connection settings
# Timezone configuration
USE_TZ = True  # Enable timezone support
TIME_ZONE = 'UTC'  # Set timezone to UTC

# Security settings for testing
# These settings are for development and should be configured properly for production
SECURE_CROSS_ORIGIN_OPENER_POLICY = None  # Allow cross-origin requests
SECURE_REFERRER_POLICY = None  # Allow referrer information

# Session configuration
# Cookie settings for session management
SESSION_COOKIE_SAMESITE = 'Lax'  # Session cookie SameSite policy
CSRF_COOKIE_SAMESITE = 'Lax'  # CSRF cookie SameSite policy